### ISSUE TITLE
Tarea terminada

### ISSUE THREAD

**Issue by JIJM1819** [interfacesweb-19-20/guia-estilos-JIJM1819#1]
@pedroprieto

**Comment by pedroprieto** [comment]
Buen trabajo, José Ignacio. Un único apunte: te falta la breve descripción de las características del sitio (has puesto un texto del estilo _lorem ipsum_). Lo de utilizar textos de relleno está bien para los prototipos, pero aquí se pedía esa descripción.

El diseño está muy chulo. Una preguntilla: el menú de navegación, ¿lo has hecho tú o has sacado el código de algún sitio? Tranquilo, que no penaliza la respuesta...

Enhorabuena, tienes un 10!! :+1:

**Comment by JIJM1819** [comment]
Ok, efectivamente no me había dado cuenta de lo de la descripción, prestaré más atención la próxima vez.
En cuanto al diseño y al menú, SI lo he buscado, yo no tengo todavía nivel para llegar a eso. Entendía que en esta práctica no se juzgaba la parte de HTML o CSS, por lo que pensé que no habría problema. Me gusta buscar recursos nuevos ya que al usarlos, intentar comprenderlos y adaptarlos a lo que haces, vas aprendiendo cosas, aunque si fuera parte a evaluar del trabajo, no presentaría algo que no fuese mío y no pudiera defender. Gracias por tu valoración. Un saludo

**Comment by pedroprieto** [comment]
Nada, no te preocupes.

Lo otro es simplemente por saber vuestro nivel, para tratar de adecuar los contenidos del temario. Me parece perfecto que lo hayas buscado. Efectivamente, la práctica no evalúa HTML ni CSS todavía. Buena actitud de investigación! :clap:
